### ISSUE TITLE
question - google home support

### ISSUE THREAD

**Issue by Zereef** [geerlingguy/pico-w-garage-door-sensor#2]
instead of home assistant is there a way to directly connect it to google home?

i dont have home assistant on my home (just starting to set up stuff)
and i have another project for the pico w that is to turn my pc on with it (powered by the internal usb header)

**Comment by geerlingguy** [comment]
That's not something I'd be interested in supporting; I intentionally avoid Google Home and Alexa since they require you to route your account through their online services.

HomeKit can be local-only (no web account required) I believe, but right now I'm just focused on HA.
