### ISSUE TITLE
Automate garage door

### ISSUE THREAD

**Issue by kdpuvvadi** [geerlingguy/pico-w-garage-door-sensor#8]
Why not integrate the garage door?

**Comment by odinb** [comment]
According to earlier comments from Jeff, it is due to security/liability issues.

**Comment by geerlingguy** [comment]
To expand on that I don't have any major qualms about doing it (in general), but I decided to not add that functionality _in my house_ for a few reasons, primarily to do with not trusting myself to think of all scenarios where I could make it do the wrong thing, from closing it on a kid's toy that isn't sitting in the way of the safety beam, to having some software bug result in both my garage doors opening up some night while we're asleep!

I may add it at some point, and it's not the hardest thing in the world, but the main purpose for this project has been to experiment with ESPHome and the Pico W :)
